In [1]:
import numpy as np
import pandas as pd 
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns
from sklearn.preprocessing import scale 
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import roc_auc_score,roc_curve
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

In [2]:
data = pd.read_csv('M30_EURUSD.csv')
data.head()

C:\Users\ihkar\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (5,6,8,9,10,12,13,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,30,31,32,33,34,35,36,37,39,40,41,42,43,44,45,46,47,48,49,50,51,55,56,58,59,61,62,64,65,67,68,70,71,73,74,76,77,79,80,82,83,85,86,88,90,92,94,96,98,100,102,104,106,108,110,112,114,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,139,140,142,143,145,146,147,148,149,150,151,152,153,154,155,156,158,160,162,164,166,168,170,172,174,176,178,179,180,181,183,185,186,188,189,191,192,194,195,197,198,200,201,203,204,206,207,209,210,212,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,385,387,389,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,420,421,422,423,424,425,426,427,428,429) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,time,open,high,low,close,ind_5,ind_6,ind_7,ind_8,ind_9,...,80_signal,90_signal,100_signal,120_signal,140_signal,160_signal,180_signal,200_signal,220_signal,240_signal
0,2017.06.26 04:00,1.11894,1.11959,1.11894,1.11942,?,?,?,?,?,...,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY
1,2017.06.26 04:30,1.11943,1.11960,1.11913,1.11942,?,?,?,?,?,...,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY
2,2017.06.26 05:00,1.11940,1.11943,1.11891,1.11922,?,?,?,?,?,...,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY
3,2017.06.26 05:30,1.11924,1.11968,1.11919,1.11957,?,?,?,?,?,...,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY
4,2017.06.26 06:00,1.11955,1.11955,1.11914,1.11926,?,?,?,?,?,...,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY

In [3]:
# soru iÅŸaretleri olan satÄ±rlar veriden silindi.
data = data.replace("?", np.nan)
data = data.dropna()
data.head()

,time,open,high,low,close,ind_5,ind_6,ind_7,ind_8,ind_9,...,80_signal,90_signal,100_signal,120_signal,140_signal,160_signal,180_signal,200_signal,220_signal,240_signal
2001,2017.08.22 20:30,1.17502,1.17538,1.17478,1.17505,-20,-19,NONE,7.142857142857143,92.85714285714286,...,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY
2002,2017.08.22 21:00,1.17505,1.17531,1.17492,1.17500,-20,-20,NONE,0.0,85.71428571428571,...,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY
2003,2017.08.22 21:30,1.17496,1.17599,1.17487,1.17583,-19,-20,BUY,35.714285714285715,78.57142857142857,...,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY
2004,2017.08.22 22:00,1.17582,1.17627,1.17565,1.17600,-17,-19,NONE,28.571428571428573,71.42857142857143,...,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY
2005,2017.08.22 22:30,1.17600,1.17630,1.17595,1.17603,-13,-17,NONE,21.428571428571427,64.28571428571429,...,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY,BUY

In [4]:
data['30_signal'].value_counts()
data.drop(index = data[data['30_signal']=='NONE'].index, inplace = True)

In [5]:
df = data.iloc[:,5:430] #datamÄ±zdan _signal kolonlarÄ±nÄ± attÄ±k
df.shape

(19440, 425)

In [6]:
#categorical olan kolonlarÄ±mÄ±z
cat_column_names = ['ind_7','ind_11','ind_24','ind_38','ind_54','ind_57','ind_60','ind_63','ind_66','ind_69','ind_72','ind_75',
                    'ind_78','ind_81','ind_84','ind_87','ind_89','ind_91','ind_93','ind_95','ind_97','ind_99','ind_101',
                    'ind_103','ind_105','ind_107','ind_109', 'ind_111', 'ind_113', 'ind_115','ind_138','ind_141','ind_144',
                    'ind_157','ind_159','ind_161','ind_163','ind_165','ind_167','ind_169','ind_171','ind_173','ind_175',
                    'ind_177','ind_182','ind_184','ind_187','ind_190','ind_193','ind_196','ind_199','ind_202','ind_205',
                    'ind_208','ind_211','ind_213','ind_384','ind_386','ind_388','ind_390']

In [7]:
# categorical kolonlarÄ±n dummy var. oalrak deÄŸiÅŸtirdik
dms = pd.get_dummies(df[cat_column_names])
dms_none_cols = dms.filter(regex = '_NONE').columns
for i in dms_none_cols:
    dms.drop(i,axis=1,inplace=True)
dms_red_cols = dms.filter(regex = '_RED').columns
for i in dms_red_cols:
    dms.drop(i,axis=1,inplace=True)

dms.head()

,ind_7_BUY,ind_7_SELL,ind_11_BUY,ind_11_SELL,ind_24_BUY,ind_24_SELL,ind_38_BUY,ind_38_SELL,ind_54_BUY,ind_54_SELL,...,ind_211_BUY,ind_211_SELL,ind_384_BUY,ind_384_SELL,ind_386_BUY,ind_386_SELL,ind_388_BUY,ind_388_SELL,ind_390_BUY,ind_390_SELL
2001,0,0,0,1,1,0,1,0,0,1,...,0,1,0,1,0,0,0,1,0,1
2002,0,0,0,1,1,0,1,0,0,1,...,0,1,0,1,0,0,0,1,0,1
2003,1,0,0,1,1,0,1,0,0,1,...,0,0,0,1,0,0,0,1,0,1
2004,0,0,0,1,1,0,1,0,1,0,...,0,0,0,1,1,0,1,0,0,1
2005,0,0,0,1,1,0,1,0,1,0,...,0,0,0,1,1,0,1,0,0,1

In [8]:
#datadan categorical olan kolonlarÄ± Ã§Ä±karÄ±yoruz ve type nÄ± deÄŸiÅŸtiriyoruz
df = df.drop(cat_column_names,axis=1).astype("float64")
df.head()

,ind_5,ind_6,ind_8,ind_9,ind_10,ind_12,ind_13,ind_14,ind_15,ind_16,...,ind_420,ind_421,ind_422,ind_423,ind_424,ind_425,ind_426,ind_427,ind_428,ind_429
2001,-20.0,-19.0,7.142857,92.857143,-85.714286,35.726149,-80.907026,5.45,7.14,8.47,...,73.0,-79.0,-99.0,202.0,0.290323,0.120805,0.537500,0.510815,0.320588,0.359703
2002,-20.0,-20.0,0.000000,85.714286,-85.714286,35.416025,-83.358058,4.95,6.28,8.02,...,74.0,-78.0,-99.0,203.0,1.000000,0.129496,0.560261,0.452514,0.312500,0.360372
2003,-19.0,-20.0,35.714286,78.571429,-42.857143,44.091954,-27.798750,7.55,6.28,7.83,...,65.0,-87.0,-107.0,195.0,0.931507,0.593103,0.533333,0.476357,0.344390,0.369380
2004,-17.0,-19.0,28.571429,71.428571,-42.857143,45.700892,-19.814109,8.70,6.44,7.43,...,64.0,-88.0,-109.0,193.0,0.950495,0.699387,0.492754,0.596421,0.383929,0.373567
2005,-13.0,-17.0,21.428571,64.285714,-42.857143,45.996248,-18.409036,4.85,6.16,7.03,...,63.0,-88.0,-109.0,193.0,1.000000,0.959016,0.503623,0.571730,0.386161,0.372810

In [9]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
pca = PCA()
# pca = PCA(n_components= 5) n_components parametresi ile 5 yeni pca'e dÃ¼ÅŸÃ¼releceÄŸi bilgisini modele sÃ¶yleyebiliriz. 
#-default olarak %100'e ulaÅŸacak ÅŸekilde bulur.

In [10]:
df_pca = pca.fit_transform(scale(df))

In [11]:
arr = np.cumsum(np.round(pca.explained_variance_ratio_, decimals = 4)*100)
arr

array([29.72, 40.62, 46.02, 49.9 , 53.01, 56.02, 58.57, 60.73, 62.69,
       64.5 , 66.19, 67.84, 69.3 , 70.68, 71.9 , 73.07, 74.21, 75.2 ,
       76.16, 77.06, 77.94, 78.74, 79.53, 80.26, 80.98, 81.67, 82.36,
       83.02, 83.65, 84.25, 84.84, 85.41, 85.95, 86.47, 86.91, 87.34,
       87.75, 88.12, 88.49, 88.84, 89.18, 89.51, 89.83, 90.13, 90.43,
       90.72, 91.  , 91.26, 91.51, 91.76, 91.99, 92.22, 92.44, 92.65,
       92.85, 93.04, 93.23, 93.41, 93.58, 93.75, 93.91, 94.07, 94.21,
       94.35, 94.49, 94.63, 94.76, 94.89, 95.02, 95.14, 95.26, 95.38,
       95.49, 95.6 , 95.71, 95.81, 95.91, 96.01, 96.11, 96.21, 96.3 ,
       96.39, 96.48, 96.57, 96.66, 96.74, 96.82, 96.9 , 96.98, 97.05,
       97.12, 97.19, 97.26, 97.33, 97.4 , 97.47, 97.53, 97.59, 97.65,
       97.71, 97.77, 97.83, 97.89, 97.95, 98.  , 98.05, 98.1 , 98.15,
       98.2 , 98.25, 98.3 , 98.35, 98.39, 98.43, 98.47, 98.51, 98.55,
       98.59, 98.63, 98.67, 98.71, 98.74, 98.77, 98.8 , 98.83, 98.86,
       98.89, 98.92, 98.95, 98.98, 99.01, 99.04, 99.07, 99.1 , 99.13,
       99.15, 99.17, 99.19, 99.21, 99.23, 99.25, 99.27, 99.29, 99.31,
       99.33, 99.35, 99.37, 99.39, 99.41, 99.43, 99.45, 99.47, 99.49,
       99.51, 99.53, 99.54, 99.55, 99.56, 99.57, 99.58, 99.59, 99.6 ,
       99.61, 99.62, 99.63, 99.64, 99.65, 99.66, 99.67, 99.68, 99.69,
       99.7 , 99.71, 99.72, 99.73, 99.74, 99.75, 99.76, 99.77, 99.78,
       99.79, 99.8 , 99.81, 99.82, 99.83, 99.84, 99.85, 99.86, 99.87,
       99.88, 99.89, 99.9 , 99.91, 99.92, 99.93, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94, 99.94,
       99.94, 99.94, 99.94, 99.94, 99.94])

In [12]:
# tmp'den bÃ¼yÃ¼k deÄŸerleri deÄŸiÅŸken olarak aldÄ±k tmp'den kÃ¼Ã§Ã¼k sayÄ±sÄ± +1 tane sonra tmpden bÃ¼yÃ¼k olanÄ± elde etmiÅŸ oluruz
tmp = 95
num_var = sum((arr < tmp)) + 1 
num_var

69

In [13]:
df_reduced = pd.DataFrame(df_pca[:,0:num_var])
df_reduced.head()

,0,1,2,3,4,5,6,7,8,9,...,59,60,61,62,63,64,65,66,67,68
0,8.816217,2.490599,1.826213,-0.228999,-2.002785,0.888982,0.486493,5.804961,-1.111886,-0.649545,...,1.143224,-0.009730,0.378814,-0.647762,-0.917145,-0.485616,-0.552713,-0.227287,-0.728028,-0.593723
1,8.868427,1.143000,2.227396,-1.082244,-1.645982,0.880413,1.020682,3.700024,-0.609006,-0.860573,...,1.302354,0.459742,0.580219,-0.003622,-0.566318,-0.339979,0.334273,-0.904298,0.041452,-0.487202
2,4.223175,-3.625572,5.847780,-1.547136,-1.665233,-0.117251,0.123568,4.447242,-0.445954,-0.539097,...,0.783392,-0.357005,0.633099,-0.155484,-0.633871,-0.804344,0.048737,0.040688,0.791409,-0.711252
3,2.751592,-4.773031,4.891633,-1.126677,-2.046001,1.369572,1.272255,3.698367,-0.148730,-1.377006,...,0.960931,0.309636,0.529828,-0.151291,-0.802349,-0.861949,-0.126983,0.445846,0.643811,-0.864890
4,1.888624,-4.973344,2.941062,-0.704649,-2.521290,2.463298,2.234898,3.533222,-0.004146,-1.512520,...,0.767227,0.076896,0.373007,0.131405,-0.707188,-0.571041,0.026899,0.364274,0.119226,-0.700085

In [14]:
# dummy e Ã§evirdiÄŸimiz datalar ile pca sonrasÄ± numeric deÄŸerlerimizi birleÅŸtiriyoruz
X = pd.concat([df_reduced,dms],axis=1)

In [15]:
#logistic regresyon iÃ§in y deÄŸiÅŸkenimizi 0 1 olarak deÄŸiÅŸtiriyoruz
data_y = data['30_signal']
cleanup_nums = {'BUY':1,'SELL':0}
data_y.replace(cleanup_nums, inplace=True)
y = np.array(data_y)
y

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [17]:
X.head()

,0,1,2,3,4,5,6,7,8,9,...,ind_211_BUY,ind_211_SELL,ind_384_BUY,ind_384_SELL,ind_386_BUY,ind_386_SELL,ind_388_BUY,ind_388_SELL,ind_390_BUY,ind_390_SELL
0,8.816217,2.490599,1.826213,-0.228999,-2.002785,0.888982,0.486493,5.804961,-1.111886,-0.649545,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8.868427,1.143000,2.227396,-1.082244,-1.645982,0.880413,1.020682,3.700024,-0.609006,-0.860573,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.223175,-3.625572,5.847780,-1.547136,-1.665233,-0.117251,0.123568,4.447242,-0.445954,-0.539097,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.751592,-4.773031,4.891633,-1.126677,-2.046001,1.369572,1.272255,3.698367,-0.148730,-1.377006,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.888624,-4.973344,2.941062,-0.704649,-2.521290,2.463298,2.234898,3.533222,-0.004146,-1.512520,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
loj = sm.Logit(y, X)
loj_model = loj.fit()
loj_model.summary()

MissingDataError: exog contains inf or nans

In [ ]:
from sklearn.linear_model import LogisticRegression
loj = LogisticRegression(solver = 'liblinear')
loj_model = loj.fit(X,y)
loj_model

In [ ]:
y_pred = loj_model.predict(X)
confusion_mat = confusion_matrix(y, y_pred)
accuracy = accuracy_score(y, y_pred)
print("Counfusion matrix: \n",confusion_mat)
print("Accuracy: ",accuracy)

In [ ]:
print(classification_report(y, y_pred))

In [ ]:
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, shuffle = False)

In [ ]:
pca1 = PCA()
pca2 = PCA()

In [ ]:
X_train_pca = pca1.fit_transform(scale(X_train))
X_test_pca = pca2.fit_transform(scale(X_test))

In [ ]:
arr1 = np.cumsum(np.round(pca1.explained_variance_ratio_, decimals = 4)*100)
arr2 = np.cumsum(np.round(pca2.explained_variance_ratio_, decimals = 4)*100)

In [ ]:
# tmp'den bÃ¼yÃ¼k deÄŸerleri deÄŸiÅŸken olarak aldÄ±k tmp'den kÃ¼Ã§Ã¼k sayÄ±sÄ± +1 tane sonra tmpden bÃ¼yÃ¼k olanÄ± elde etmiÅŸ oluruz
tmp = 0.95
num_var1 = sum((arr1 < tmp*100)) + 1 
num_var2 = sum((arr2 < tmp*100)) + 1 
print(num_var1, num_var2)

In [ ]:
X_train_reduced = pd.DataFrame(X_train_pca[:,0:num_var1])
X_test_reduced = pd.DataFrame(X_test_pca[:,0:num_var2])

In [ ]:
loj1 = LogisticRegression(solver = 'liblinear')
loj1_model = loj1.fit(X_train_reduced,y_train)
loj1_model

In [ ]:
y_pred_1 = loj1_model.predict(X_train_reduced)
confusion_mat = confusion_matrix(y_train, y_pred_1)
accuracy = accuracy_score(y_train, y_pred_1)
print("Counfusion matrix: \n",confusion_mat)
print("Accuracy: ",accuracy)

In [ ]:
print(classification_report(y_train, y_pred_1))

In [ ]:
loj2 = LogisticRegression(solver = 'liblinear')
loj2_model = loj2.fit(X_test_reduced,y_test)
loj2_model

In [ ]:
y_pred_2 = loj2_model.predict(X_test_reduced)
confusion_mat = confusion_matrix(y_test, y_pred_2)
accuracy = accuracy_score(y_test, y_pred_2)
print("Counfusion matrix: \n",confusion_mat)
print("Accuracy: ",accuracy)

In [ ]:
data.loc['date'].['2007']